apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysqldb
  name: mysqldb
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysqldb
    spec:
      containers:
      - image: shichoc/mysqlshop:latest
        imagePullPolicy: IfNotPresent
        name: mysqlshop
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: passwd
        resources: {}
status: {}

