apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
  namespace: k1s
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: broker
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: broker
  name: broker
  namespace: k1s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: broker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: broker
    spec:
      containers:
      - image: josh951753/broker:1.0
        imagePullPolicy: Always
        name: broker
        env:
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq
          - name: SPRING_RABBITMQ_PORT
            value: 5672
          - name: SPRING_RABBITMQ_USER
            value: guest
          - name: SPRING_RABBITMQ_PASSWORD
            value: guest
        ports:
          - containerPort: 8081
        env:
status: {}
