apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-service
  name: product-service
  namespace: k1s
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: product-service
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-service
  name: product-service
  namespace: k1s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-service
    spec:
      containers:
      - image: josh951753/product:1.0
        imagePullPolicy: Always
        name: product-service
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysqldb:3306/simpleshop
          - name: SPRING_DATASOURCE_PASSWORD
            value: passwd
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq
          - name: SPRING_RABBITMQ_PORT
            value: 5672
          - name: SPRING_RABBITMQ_USER
            value: guest
          - name: SPRING_RABBITMQ_PASSWORD
            value: guest
        ports:
          - containerPort: 8082
        env:
status: {}

